services:
  postgres:
    image: postgres:17.2
    restart: "no"
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hockey_monitoring_db
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  hockey-monitoring:
    image: hockey-monitoring:latest
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres:5432
      POSTGRES_DB_NAME: hockey_monitoring_db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root
    depends_on:
      - postgres

volumes:
  postgres_data:
